// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "93f3fd5b0853ed8a3c5b795ca3196079065b860248f76c11d5d85aa7fd5542c7")
