// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "34004bfc986677207d9ae4a0684cd19b403c002079bad2f29d89c95615cb39de")
