// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "9c042678ff389e67fe04a7addcbb86fa0a19bef461bd4fd70193e857f8516507")
