// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "8a8c5709b76f8cc8bbd10a5e04456e4d506debcd464baab484dffd771928ff77")
