// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: datadog/trace/agent_payload.proto

package trace

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AgentPayload represents payload the agent sends to the intake.
type AgentPayload struct {
	// hostName specifies hostname of where the agent is running.
	HostName string `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	// env specifies `env` set in agent configuration.
	Env string `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	// tracerPayloads specifies list of the payloads received from tracers.
	TracerPayloads []*TracerPayload `protobuf:"bytes,5,rep,name=tracerPayloads,proto3" json:"tracerPayloads,omitempty"`
	// tags specifies tags common in all `tracerPayloads`.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// agentVersion specifies version of the agent.
	AgentVersion string `protobuf:"bytes,7,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	// targetTPS holds `TargetTPS` value in AgentConfig.
	TargetTPS float64 `protobuf:"fixed64,8,opt,name=targetTPS,proto3" json:"targetTPS,omitempty"`
	// errorTPS holds `ErrorTPS` value in AgentConfig.
	ErrorTPS float64 `protobuf:"fixed64,9,opt,name=errorTPS,proto3" json:"errorTPS,omitempty"`
}

func (m *AgentPayload) Reset()      { *m = AgentPayload{} }
func (*AgentPayload) ProtoMessage() {}
func (*AgentPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f406bc6ae61e631b, []int{0}
}
func (m *AgentPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgentPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgentPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgentPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentPayload.Merge(m, src)
}
func (m *AgentPayload) XXX_Size() int {
	return m.Size()
}
func (m *AgentPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AgentPayload proto.InternalMessageInfo

func (m *AgentPayload) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *AgentPayload) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *AgentPayload) GetTracerPayloads() []*TracerPayload {
	if m != nil {
		return m.TracerPayloads
	}
	return nil
}

func (m *AgentPayload) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AgentPayload) GetAgentVersion() string {
	if m != nil {
		return m.AgentVersion
	}
	return ""
}

func (m *AgentPayload) GetTargetTPS() float64 {
	if m != nil {
		return m.TargetTPS
	}
	return 0
}

func (m *AgentPayload) GetErrorTPS() float64 {
	if m != nil {
		return m.ErrorTPS
	}
	return 0
}

func init() {
	proto.RegisterType((*AgentPayload)(nil), "datadog.trace.AgentPayload")
	proto.RegisterMapType((map[string]string)(nil), "datadog.trace.AgentPayload.TagsEntry")
}

func init() { proto.RegisterFile("datadog/trace/agent_payload.proto", fileDescriptor_f406bc6ae61e631b) }

var fileDescriptor_f406bc6ae61e631b = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xbd, 0x4e, 0x02, 0x41,
	0x10, 0xc7, 0x6f, 0x41, 0x90, 0x5b, 0xd1, 0x98, 0x0d, 0xc5, 0x85, 0x90, 0x09, 0x92, 0x98, 0x50,
	0xdd, 0x25, 0x5a, 0xf8, 0xd1, 0x69, 0xb4, 0xb1, 0x30, 0xe4, 0x24, 0x16, 0x36, 0x66, 0x91, 0xcd,
	0x6a, 0xc0, 0xdb, 0xcb, 0xde, 0x4a, 0x42, 0xe7, 0x23, 0xf8, 0x18, 0x3e, 0x8a, 0x25, 0x85, 0x05,
	0xa5, 0x2c, 0x8d, 0x25, 0x8f, 0x60, 0x76, 0xef, 0x72, 0x72, 0x34, 0x9b, 0x99, 0xff, 0xcc, 0x6f,
	0x76, 0x3e, 0xf0, 0xc1, 0x90, 0x2a, 0x3a, 0x14, 0x3c, 0x50, 0x92, 0x3e, 0xb1, 0x80, 0x72, 0x16,
	0xa9, 0xc7, 0x98, 0x4e, 0xc7, 0x82, 0x0e, 0xfd, 0x58, 0x0a, 0x25, 0xc8, 0x6e, 0x96, 0xe2, 0xdb,
	0x94, 0x66, 0xa7, 0x48, 0xd8, 0x57, 0x16, 0x91, 0xce, 0x77, 0x09, 0xd7, 0x2f, 0x4c, 0xa9, 0x5e,
	0x2a, 0x93, 0x26, 0xae, 0x3d, 0x8b, 0x44, 0xdd, 0xd2, 0x57, 0xe6, 0xa1, 0x36, 0xea, 0xba, 0x61,
	0xee, 0x93, 0x7d, 0x5c, 0x66, 0xd1, 0xc4, 0x2b, 0x59, 0xd9, 0x98, 0xe4, 0x0a, 0xef, 0xa5, 0x65,
	0x33, 0x3c, 0xf1, 0x2a, 0xed, 0x72, 0x77, 0xe7, 0xa8, 0xe5, 0x17, 0x5a, 0xf1, 0xfb, 0xeb, 0x49,
	0xe1, 0x06, 0x43, 0xce, 0xf0, 0x96, 0xa2, 0x3c, 0xf1, 0xaa, 0x96, 0x3d, 0xdc, 0x60, 0xd7, 0xdb,
	0xf3, 0xfb, 0x94, 0x27, 0xd7, 0x91, 0x92, 0xd3, 0xd0, 0x22, 0xa4, 0x83, 0xeb, 0x76, 0x13, 0xf7,
	0x4c, 0x26, 0x2f, 0x22, 0xf2, 0xb6, 0x6d, 0x6f, 0x05, 0x8d, 0xb4, 0xb0, 0xab, 0xa8, 0xe4, 0x4c,
	0xf5, 0x7b, 0x77, 0x5e, 0xad, 0x8d, 0xba, 0x28, 0xfc, 0x17, 0xcc, 0xc0, 0x4c, 0x4a, 0x21, 0x4d,
	0xd0, 0xb5, 0xc1, 0xdc, 0x6f, 0x9e, 0x60, 0x37, 0xff, 0xd0, 0x4c, 0x3f, 0x62, 0xd3, 0x6c, 0x29,
	0xc6, 0x24, 0x0d, 0x5c, 0x99, 0xd0, 0xf1, 0x1b, 0xcb, 0x36, 0x92, 0x3a, 0xe7, 0xa5, 0x53, 0x74,
	0x79, 0x33, 0x5b, 0x80, 0x33, 0x5f, 0x80, 0xb3, 0x5a, 0x00, 0x7a, 0xd7, 0x80, 0x3e, 0x35, 0xa0,
	0x2f, 0x0d, 0x68, 0xa6, 0x01, 0xfd, 0x68, 0x40, 0xbf, 0x1a, 0x9c, 0x95, 0x06, 0xf4, 0xb1, 0x04,
	0x67, 0xb6, 0x04, 0x67, 0xbe, 0x04, 0xe7, 0xa1, 0x11, 0x8f, 0x78, 0x60, 0xef, 0x12, 0xc4, 0x03,
	0x2e, 0xd2, 0x8b, 0x0d, 0xaa, 0x56, 0x39, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x12, 0x89, 0x4a,
	0x33, 0x01, 0x02, 0x00, 0x00,
}

func (this *AgentPayload) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AgentPayload)
	if !ok {
		that2, ok := that.(AgentPayload)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.HostName != that1.HostName {
		return false
	}
	if this.Env != that1.Env {
		return false
	}
	if len(this.TracerPayloads) != len(that1.TracerPayloads) {
		return false
	}
	for i := range this.TracerPayloads {
		if !this.TracerPayloads[i].Equal(that1.TracerPayloads[i]) {
			return false
		}
	}
	if len(this.Tags) != len(that1.Tags) {
		return false
	}
	for i := range this.Tags {
		if this.Tags[i] != that1.Tags[i] {
			return false
		}
	}
	if this.AgentVersion != that1.AgentVersion {
		return false
	}
	if this.TargetTPS != that1.TargetTPS {
		return false
	}
	if this.ErrorTPS != that1.ErrorTPS {
		return false
	}
	return true
}
func (this *AgentPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&trace.AgentPayload{")
	s = append(s, "HostName: "+fmt.Sprintf("%#v", this.HostName)+",\n")
	s = append(s, "Env: "+fmt.Sprintf("%#v", this.Env)+",\n")
	if this.TracerPayloads != nil {
		s = append(s, "TracerPayloads: "+fmt.Sprintf("%#v", this.TracerPayloads)+",\n")
	}
	keysForTags := make([]string, 0, len(this.Tags))
	for k, _ := range this.Tags {
		keysForTags = append(keysForTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTags)
	mapStringForTags := "map[string]string{"
	for _, k := range keysForTags {
		mapStringForTags += fmt.Sprintf("%#v: %#v,", k, this.Tags[k])
	}
	mapStringForTags += "}"
	if this.Tags != nil {
		s = append(s, "Tags: "+mapStringForTags+",\n")
	}
	s = append(s, "AgentVersion: "+fmt.Sprintf("%#v", this.AgentVersion)+",\n")
	s = append(s, "TargetTPS: "+fmt.Sprintf("%#v", this.TargetTPS)+",\n")
	s = append(s, "ErrorTPS: "+fmt.Sprintf("%#v", this.ErrorTPS)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAgentPayload(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *AgentPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgentPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgentPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ErrorTPS != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.ErrorTPS))))
		i--
		dAtA[i] = 0x49
	}
	if m.TargetTPS != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.TargetTPS))))
		i--
		dAtA[i] = 0x41
	}
	if len(m.AgentVersion) > 0 {
		i -= len(m.AgentVersion)
		copy(dAtA[i:], m.AgentVersion)
		i = encodeVarintAgentPayload(dAtA, i, uint64(len(m.AgentVersion)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Tags) > 0 {
		for k := range m.Tags {
			v := m.Tags[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintAgentPayload(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintAgentPayload(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintAgentPayload(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.TracerPayloads) > 0 {
		for iNdEx := len(m.TracerPayloads) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TracerPayloads[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAgentPayload(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Env) > 0 {
		i -= len(m.Env)
		copy(dAtA[i:], m.Env)
		i = encodeVarintAgentPayload(dAtA, i, uint64(len(m.Env)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.HostName) > 0 {
		i -= len(m.HostName)
		copy(dAtA[i:], m.HostName)
		i = encodeVarintAgentPayload(dAtA, i, uint64(len(m.HostName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAgentPayload(dAtA []byte, offset int, v uint64) int {
	offset -= sovAgentPayload(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AgentPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.HostName)
	if l > 0 {
		n += 1 + l + sovAgentPayload(uint64(l))
	}
	l = len(m.Env)
	if l > 0 {
		n += 1 + l + sovAgentPayload(uint64(l))
	}
	if len(m.TracerPayloads) > 0 {
		for _, e := range m.TracerPayloads {
			l = e.Size()
			n += 1 + l + sovAgentPayload(uint64(l))
		}
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovAgentPayload(uint64(len(k))) + 1 + len(v) + sovAgentPayload(uint64(len(v)))
			n += mapEntrySize + 1 + sovAgentPayload(uint64(mapEntrySize))
		}
	}
	l = len(m.AgentVersion)
	if l > 0 {
		n += 1 + l + sovAgentPayload(uint64(l))
	}
	if m.TargetTPS != 0 {
		n += 9
	}
	if m.ErrorTPS != 0 {
		n += 9
	}
	return n
}

func sovAgentPayload(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAgentPayload(x uint64) (n int) {
	return sovAgentPayload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AgentPayload) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForTracerPayloads := "[]*TracerPayload{"
	for _, f := range this.TracerPayloads {
		repeatedStringForTracerPayloads += strings.Replace(fmt.Sprintf("%v", f), "TracerPayload", "TracerPayload", 1) + ","
	}
	repeatedStringForTracerPayloads += "}"
	keysForTags := make([]string, 0, len(this.Tags))
	for k, _ := range this.Tags {
		keysForTags = append(keysForTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTags)
	mapStringForTags := "map[string]string{"
	for _, k := range keysForTags {
		mapStringForTags += fmt.Sprintf("%v: %v,", k, this.Tags[k])
	}
	mapStringForTags += "}"
	s := strings.Join([]string{`&AgentPayload{`,
		`HostName:` + fmt.Sprintf("%v", this.HostName) + `,`,
		`Env:` + fmt.Sprintf("%v", this.Env) + `,`,
		`TracerPayloads:` + repeatedStringForTracerPayloads + `,`,
		`Tags:` + mapStringForTags + `,`,
		`AgentVersion:` + fmt.Sprintf("%v", this.AgentVersion) + `,`,
		`TargetTPS:` + fmt.Sprintf("%v", this.TargetTPS) + `,`,
		`ErrorTPS:` + fmt.Sprintf("%v", this.ErrorTPS) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAgentPayload(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AgentPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgentPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgentPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgentPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TracerPayloads", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentPayload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TracerPayloads = append(m.TracerPayloads, &TracerPayload{})
			if err := m.TracerPayloads[len(m.TracerPayloads)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAgentPayload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAgentPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAgentPayload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAgentPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthAgentPayload
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthAgentPayload
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAgentPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthAgentPayload
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthAgentPayload
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipAgentPayload(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthAgentPayload
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgentPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgentPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetTPS", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.TargetTPS = float64(math.Float64frombits(v))
		case 9:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorTPS", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.ErrorTPS = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipAgentPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgentPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAgentPayload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAgentPayload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgentPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAgentPayload
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAgentPayload
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAgentPayload
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAgentPayload        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAgentPayload          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAgentPayload = fmt.Errorf("proto: unexpected end of group")
)
