// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: datadog/trace/tracer_payload.proto

package trace

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// TraceChunk represents a list of spans with the same trace id.
type TraceChunk struct {
	// priority specifies sampling priority of the trace.
	Priority int32 `protobuf:"varint,1,opt,name=priority,proto3" json:"priority" msg:"priority"`
	// origin specifies origin product ("lambda", "rum", etc.) of the trace.
	Origin string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin" msg:"origin"`
	// spans specifies list of containing spans.
	Spans []*Span `protobuf:"bytes,3,rep,name=spans,proto3" json:"spans" msg:"spans"`
	// tags specifies tags common in all `spans`.
	Tags map[string]string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags" msg:"tags" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// droppedTrace specifies whether the trace was dropped by samplers or not.
	DroppedTrace bool `protobuf:"varint,5,opt,name=droppedTrace,proto3" json:"dropped_trace" msg:"dropped_trace"`
}

func (m *TraceChunk) Reset()      { *m = TraceChunk{} }
func (*TraceChunk) ProtoMessage() {}
func (*TraceChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbc00970b529f30, []int{0}
}
func (m *TraceChunk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TraceChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TraceChunk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TraceChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceChunk.Merge(m, src)
}
func (m *TraceChunk) XXX_Size() int {
	return m.Size()
}
func (m *TraceChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceChunk.DiscardUnknown(m)
}

var xxx_messageInfo_TraceChunk proto.InternalMessageInfo

func (m *TraceChunk) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *TraceChunk) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *TraceChunk) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *TraceChunk) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TraceChunk) GetDroppedTrace() bool {
	if m != nil {
		return m.DroppedTrace
	}
	return false
}

// TracerPayload represents a payload the trace agent receives from tracers.
type TracerPayload struct {
	// containerID specifies the ID of the container where the tracer is running on.
	ContainerID string `protobuf:"bytes,1,opt,name=containerID,proto3" json:"container_id" msg:"container_id"`
	// languageName specifies language of the tracer.
	LanguageName string `protobuf:"bytes,2,opt,name=languageName,proto3" json:"language_name" msg:"language_name"`
	// languageVersion specifies language version of the tracer.
	LanguageVersion string `protobuf:"bytes,3,opt,name=languageVersion,proto3" json:"language_version" msg:"language_version"`
	// tracerVersion specifies version of the tracer.
	TracerVersion string `protobuf:"bytes,4,opt,name=tracerVersion,proto3" json:"tracer_version" msg:"tracer_version"`
	// runtimeID specifies V4 UUID representation of a tracer session.
	RuntimeID string `protobuf:"bytes,5,opt,name=runtimeID,proto3" json:"runtime_id" msg:"runtime_id"`
	// chunks specifies list of containing trace chunks.
	Chunks []*TraceChunk `protobuf:"bytes,6,rep,name=chunks,proto3" json:"chunks" msg:"chunks"`
	// tags specifies tags common in all `chunks`.
	Tags map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags" msg:"tags" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// env specifies `env` tag that set with the tracer.
	Env string `protobuf:"bytes,8,opt,name=env,proto3" json:"env" msg:"env"`
	// hostname specifies hostname of where the tracer is running.
	Hostname string `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname" msg:"hostname"`
	// version specifies `version` tag that set with the tracer.
	AppVersion string `protobuf:"bytes,10,opt,name=appVersion,proto3" json:"app_version" msg:"app_version"`
}

func (m *TracerPayload) Reset()      { *m = TracerPayload{} }
func (*TracerPayload) ProtoMessage() {}
func (*TracerPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffbc00970b529f30, []int{1}
}
func (m *TracerPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TracerPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TracerPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TracerPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracerPayload.Merge(m, src)
}
func (m *TracerPayload) XXX_Size() int {
	return m.Size()
}
func (m *TracerPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_TracerPayload.DiscardUnknown(m)
}

var xxx_messageInfo_TracerPayload proto.InternalMessageInfo

func (m *TracerPayload) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *TracerPayload) GetLanguageName() string {
	if m != nil {
		return m.LanguageName
	}
	return ""
}

func (m *TracerPayload) GetLanguageVersion() string {
	if m != nil {
		return m.LanguageVersion
	}
	return ""
}

func (m *TracerPayload) GetTracerVersion() string {
	if m != nil {
		return m.TracerVersion
	}
	return ""
}

func (m *TracerPayload) GetRuntimeID() string {
	if m != nil {
		return m.RuntimeID
	}
	return ""
}

func (m *TracerPayload) GetChunks() []*TraceChunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func (m *TracerPayload) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TracerPayload) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *TracerPayload) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *TracerPayload) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func init() {
	proto.RegisterType((*TraceChunk)(nil), "datadog.trace.TraceChunk")
	proto.RegisterMapType((map[string]string)(nil), "datadog.trace.TraceChunk.TagsEntry")
	proto.RegisterType((*TracerPayload)(nil), "datadog.trace.TracerPayload")
	proto.RegisterMapType((map[string]string)(nil), "datadog.trace.TracerPayload.TagsEntry")
}

func init() {
	proto.RegisterFile("datadog/trace/tracer_payload.proto", fileDescriptor_ffbc00970b529f30)
}

var fileDescriptor_ffbc00970b529f30 = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0xa6, 0x09, 0xf5, 0xa6, 0x29, 0x65, 0x1b, 0x55, 0x26, 0x87, 0xdd, 0x68, 0x41,
	0x55, 0xc4, 0x21, 0x91, 0xca, 0x01, 0xd4, 0x13, 0x72, 0x8b, 0x44, 0x11, 0x7f, 0xaa, 0xa5, 0x42,
	0x88, 0x4b, 0xb4, 0x6d, 0x8c, 0x6b, 0xb5, 0xb1, 0x2d, 0xdb, 0x89, 0xd4, 0x1b, 0x8f, 0xc0, 0x15,
	0xf1, 0x02, 0x3c, 0x0a, 0xc7, 0x1e, 0x7b, 0x5a, 0x51, 0xf7, 0x82, 0x7c, 0xaa, 0xfc, 0x04, 0xc8,
	0xb3, 0xb6, 0x13, 0x57, 0x20, 0x21, 0x2e, 0x51, 0xe6, 0x37, 0xfb, 0x7d, 0xf6, 0xec, 0xcc, 0x18,
	0xb1, 0xb1, 0x88, 0xc4, 0xd8, 0xb3, 0x87, 0x51, 0x20, 0x8e, 0x2d, 0xf5, 0x1b, 0x8c, 0x7c, 0x71,
	0x7e, 0xe6, 0x89, 0xf1, 0xc0, 0x0f, 0xbc, 0xc8, 0xc3, 0xed, 0xfc, 0xcc, 0x00, 0xb2, 0x5d, 0x66,
	0x7b, 0xb6, 0x37, 0x84, 0xd4, 0xd1, 0xf4, 0xd3, 0x30, 0x8b, 0x20, 0x80, 0x7f, 0x4a, 0xd2, 0x35,
	0xaa, 0xb6, 0xa1, 0x2f, 0x5c, 0x95, 0x61, 0x5f, 0xeb, 0x08, 0x1d, 0x66, 0x70, 0xf7, 0x64, 0xea,
	0x9e, 0xe2, 0x1d, 0xb4, 0xe2, 0x07, 0x8e, 0x17, 0x38, 0xd1, 0xb9, 0xa1, 0xf5, 0xb4, 0x7e, 0xc3,
	0x24, 0x89, 0xa4, 0x25, 0x4b, 0x25, 0x5d, 0x9b, 0x84, 0xf6, 0x0e, 0x2b, 0x00, 0xe3, 0x65, 0x0e,
	0x6f, 0xa3, 0xa6, 0x17, 0x38, 0xb6, 0xe3, 0x1a, 0x4b, 0x3d, 0xad, 0xaf, 0x9b, 0xdd, 0x44, 0xd2,
	0x9c, 0xa4, 0x92, 0xae, 0x82, 0x4e, 0x85, 0x8c, 0xe7, 0x1c, 0xef, 0xa2, 0x46, 0xf6, 0x32, 0xa1,
	0x51, 0xef, 0xd5, 0xfb, 0xad, 0xed, 0x8d, 0x41, 0xa5, 0xb6, 0xc1, 0x3b, 0x5f, 0xb8, 0xa6, 0x91,
	0x48, 0xaa, 0x4e, 0xa5, 0x92, 0xb6, 0xc0, 0x06, 0x22, 0xc6, 0x15, 0xc5, 0x6f, 0xd1, 0x72, 0x24,
	0xec, 0xd0, 0x58, 0x06, 0x8f, 0x07, 0xb7, 0x3c, 0xe6, 0xd5, 0x0d, 0x0e, 0x85, 0x1d, 0x3e, 0x77,
	0xa3, 0xe0, 0xdc, 0xdc, 0x4c, 0x24, 0x05, 0x51, 0x2a, 0x29, 0x02, 0xcb, 0x2c, 0x60, 0x1c, 0x18,
	0x7e, 0x85, 0x56, 0xc7, 0x81, 0xe7, 0xfb, 0xd6, 0x18, 0xc4, 0x46, 0xa3, 0xa7, 0xf5, 0x57, 0xcc,
	0x7e, 0x22, 0x69, 0x3b, 0xe7, 0x23, 0xf0, 0x4e, 0x25, 0xdd, 0x00, 0x71, 0x85, 0x32, 0x5e, 0x51,
	0x77, 0x9f, 0x20, 0xbd, 0x7c, 0x30, 0x5e, 0x47, 0xf5, 0x53, 0x4b, 0xdd, 0xad, 0xce, 0xb3, 0xbf,
	0xb8, 0x83, 0x1a, 0x33, 0x71, 0x36, 0xb5, 0xd4, 0xad, 0x71, 0x15, 0xec, 0x2c, 0x3d, 0xd5, 0xd8,
	0xb7, 0x26, 0x6a, 0x83, 0x45, 0x70, 0xa0, 0x06, 0x00, 0xbf, 0x40, 0xad, 0x63, 0xcf, 0x8d, 0x84,
	0xe3, 0x5a, 0xc1, 0xfe, 0x9e, 0x72, 0x31, 0xb7, 0x12, 0x49, 0x57, 0x4b, 0x3c, 0x72, 0xc6, 0xa9,
	0xa4, 0x18, 0x5e, 0x6b, 0x11, 0x32, 0xbe, 0x28, 0xcd, 0x4a, 0x3c, 0x13, 0xae, 0x3d, 0x15, 0xb6,
	0xf5, 0x46, 0x4c, 0xf2, 0x87, 0xab, 0x12, 0x0b, 0x3e, 0x72, 0xc5, 0x64, 0x5e, 0x62, 0x85, 0x32,
	0x5e, 0x51, 0xe3, 0x0f, 0xe8, 0x6e, 0x11, 0xbf, 0xb7, 0x82, 0xd0, 0xf1, 0x5c, 0xa3, 0x0e, 0x86,
	0x83, 0x44, 0xd2, 0xf5, 0x52, 0x3a, 0x53, 0xb9, 0x54, 0xd2, 0xcd, 0xaa, 0x67, 0x9e, 0x60, 0xfc,
	0xb6, 0x0d, 0x3e, 0x40, 0x6d, 0xb5, 0x04, 0x85, 0xef, 0x32, 0xf8, 0x3e, 0x4a, 0x24, 0x5d, 0xcb,
	0xb7, 0x63, 0xee, 0xda, 0x51, 0x9d, 0xac, 0x60, 0xc6, 0xab, 0x06, 0xf8, 0x19, 0xd2, 0x83, 0xa9,
	0x1b, 0x39, 0x13, 0x6b, 0x7f, 0x0f, 0x3a, 0xab, 0x9b, 0x2c, 0x91, 0x14, 0xe5, 0x50, 0xdd, 0xdf,
	0x3a, 0x38, 0xcd, 0x11, 0xe3, 0x73, 0x11, 0x7e, 0x8d, 0x9a, 0xc7, 0xd9, 0x3c, 0x85, 0x46, 0x13,
	0x26, 0xee, 0xfe, 0x5f, 0x27, 0x4e, 0xed, 0x80, 0x3a, 0x5c, 0xee, 0x80, 0x0a, 0x19, 0xcf, 0x39,
	0xe6, 0xf9, 0xf8, 0xde, 0x01, 0xb3, 0xad, 0x3f, 0x99, 0x15, 0x03, 0xf0, 0xcf, 0x13, 0xbc, 0x85,
	0xea, 0x96, 0x3b, 0x33, 0x56, 0xa0, 0xbc, 0x4e, 0x22, 0x69, 0x16, 0xa6, 0x92, 0xea, 0x70, 0xd2,
	0x72, 0x67, 0x8c, 0x67, 0x24, 0xdb, 0xf7, 0x13, 0x2f, 0x8c, 0xb2, 0x9e, 0x1a, 0x3a, 0x1c, 0x86,
	0x7d, 0x2f, 0x58, 0xb9, 0xef, 0x05, 0x60, 0xbc, 0xcc, 0xe1, 0x3d, 0x84, 0x84, 0xef, 0x17, 0x7d,
	0x41, 0xa0, 0x7e, 0x98, 0x48, 0xda, 0x12, 0xbe, 0xbf, 0xd0, 0x94, 0x7b, 0x60, 0xb0, 0xc0, 0x18,
	0x5f, 0xd0, 0xfd, 0xf7, 0x76, 0x98, 0x2f, 0x2f, 0xae, 0x48, 0xed, 0xf2, 0x8a, 0xd4, 0x6e, 0xae,
	0x88, 0xf6, 0x39, 0x26, 0xda, 0xf7, 0x98, 0x68, 0x3f, 0x62, 0xa2, 0x5d, 0xc4, 0x44, 0xfb, 0x19,
	0x13, 0xed, 0x57, 0x4c, 0x6a, 0x37, 0x31, 0xd1, 0xbe, 0x5c, 0x93, 0xda, 0xc5, 0x35, 0xa9, 0x5d,
	0x5e, 0x93, 0xda, 0xc7, 0x8e, 0x7f, 0x6a, 0xab, 0x8f, 0xe5, 0xd0, 0x3f, 0xb2, 0x3d, 0xf5, 0x41,
	0x3c, 0x6a, 0x02, 0x79, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x10, 0x91, 0x78, 0x7f, 0x05,
	0x00, 0x00,
}

func (this *TraceChunk) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TraceChunk)
	if !ok {
		that2, ok := that.(TraceChunk)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Priority != that1.Priority {
		return false
	}
	if this.Origin != that1.Origin {
		return false
	}
	if len(this.Spans) != len(that1.Spans) {
		return false
	}
	for i := range this.Spans {
		if !this.Spans[i].Equal(that1.Spans[i]) {
			return false
		}
	}
	if len(this.Tags) != len(that1.Tags) {
		return false
	}
	for i := range this.Tags {
		if this.Tags[i] != that1.Tags[i] {
			return false
		}
	}
	if this.DroppedTrace != that1.DroppedTrace {
		return false
	}
	return true
}
func (this *TracerPayload) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TracerPayload)
	if !ok {
		that2, ok := that.(TracerPayload)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ContainerID != that1.ContainerID {
		return false
	}
	if this.LanguageName != that1.LanguageName {
		return false
	}
	if this.LanguageVersion != that1.LanguageVersion {
		return false
	}
	if this.TracerVersion != that1.TracerVersion {
		return false
	}
	if this.RuntimeID != that1.RuntimeID {
		return false
	}
	if len(this.Chunks) != len(that1.Chunks) {
		return false
	}
	for i := range this.Chunks {
		if !this.Chunks[i].Equal(that1.Chunks[i]) {
			return false
		}
	}
	if len(this.Tags) != len(that1.Tags) {
		return false
	}
	for i := range this.Tags {
		if this.Tags[i] != that1.Tags[i] {
			return false
		}
	}
	if this.Env != that1.Env {
		return false
	}
	if this.Hostname != that1.Hostname {
		return false
	}
	if this.AppVersion != that1.AppVersion {
		return false
	}
	return true
}
func (this *TraceChunk) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&trace.TraceChunk{")
	s = append(s, "Priority: "+fmt.Sprintf("%#v", this.Priority)+",\n")
	s = append(s, "Origin: "+fmt.Sprintf("%#v", this.Origin)+",\n")
	if this.Spans != nil {
		s = append(s, "Spans: "+fmt.Sprintf("%#v", this.Spans)+",\n")
	}
	keysForTags := make([]string, 0, len(this.Tags))
	for k, _ := range this.Tags {
		keysForTags = append(keysForTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTags)
	mapStringForTags := "map[string]string{"
	for _, k := range keysForTags {
		mapStringForTags += fmt.Sprintf("%#v: %#v,", k, this.Tags[k])
	}
	mapStringForTags += "}"
	if this.Tags != nil {
		s = append(s, "Tags: "+mapStringForTags+",\n")
	}
	s = append(s, "DroppedTrace: "+fmt.Sprintf("%#v", this.DroppedTrace)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TracerPayload) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&trace.TracerPayload{")
	s = append(s, "ContainerID: "+fmt.Sprintf("%#v", this.ContainerID)+",\n")
	s = append(s, "LanguageName: "+fmt.Sprintf("%#v", this.LanguageName)+",\n")
	s = append(s, "LanguageVersion: "+fmt.Sprintf("%#v", this.LanguageVersion)+",\n")
	s = append(s, "TracerVersion: "+fmt.Sprintf("%#v", this.TracerVersion)+",\n")
	s = append(s, "RuntimeID: "+fmt.Sprintf("%#v", this.RuntimeID)+",\n")
	if this.Chunks != nil {
		s = append(s, "Chunks: "+fmt.Sprintf("%#v", this.Chunks)+",\n")
	}
	keysForTags := make([]string, 0, len(this.Tags))
	for k, _ := range this.Tags {
		keysForTags = append(keysForTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTags)
	mapStringForTags := "map[string]string{"
	for _, k := range keysForTags {
		mapStringForTags += fmt.Sprintf("%#v: %#v,", k, this.Tags[k])
	}
	mapStringForTags += "}"
	if this.Tags != nil {
		s = append(s, "Tags: "+mapStringForTags+",\n")
	}
	s = append(s, "Env: "+fmt.Sprintf("%#v", this.Env)+",\n")
	s = append(s, "Hostname: "+fmt.Sprintf("%#v", this.Hostname)+",\n")
	s = append(s, "AppVersion: "+fmt.Sprintf("%#v", this.AppVersion)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTracerPayload(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TraceChunk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TraceChunk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TraceChunk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DroppedTrace {
		i--
		if m.DroppedTrace {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.Tags) > 0 {
		for k := range m.Tags {
			v := m.Tags[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintTracerPayload(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintTracerPayload(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTracerPayload(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Spans) > 0 {
		for iNdEx := len(m.Spans) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Spans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTracerPayload(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Origin) > 0 {
		i -= len(m.Origin)
		copy(dAtA[i:], m.Origin)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.Origin)))
		i--
		dAtA[i] = 0x12
	}
	if m.Priority != 0 {
		i = encodeVarintTracerPayload(dAtA, i, uint64(m.Priority))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TracerPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TracerPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TracerPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AppVersion) > 0 {
		i -= len(m.AppVersion)
		copy(dAtA[i:], m.AppVersion)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.AppVersion)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Hostname) > 0 {
		i -= len(m.Hostname)
		copy(dAtA[i:], m.Hostname)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.Hostname)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Env) > 0 {
		i -= len(m.Env)
		copy(dAtA[i:], m.Env)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.Env)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Tags) > 0 {
		for k := range m.Tags {
			v := m.Tags[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintTracerPayload(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintTracerPayload(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTracerPayload(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Chunks) > 0 {
		for iNdEx := len(m.Chunks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chunks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTracerPayload(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RuntimeID) > 0 {
		i -= len(m.RuntimeID)
		copy(dAtA[i:], m.RuntimeID)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.RuntimeID)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TracerVersion) > 0 {
		i -= len(m.TracerVersion)
		copy(dAtA[i:], m.TracerVersion)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.TracerVersion)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LanguageVersion) > 0 {
		i -= len(m.LanguageVersion)
		copy(dAtA[i:], m.LanguageVersion)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.LanguageVersion)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LanguageName) > 0 {
		i -= len(m.LanguageName)
		copy(dAtA[i:], m.LanguageName)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.LanguageName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContainerID) > 0 {
		i -= len(m.ContainerID)
		copy(dAtA[i:], m.ContainerID)
		i = encodeVarintTracerPayload(dAtA, i, uint64(len(m.ContainerID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTracerPayload(dAtA []byte, offset int, v uint64) int {
	offset -= sovTracerPayload(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TraceChunk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Priority != 0 {
		n += 1 + sovTracerPayload(uint64(m.Priority))
	}
	l = len(m.Origin)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	if len(m.Spans) > 0 {
		for _, e := range m.Spans {
			l = e.Size()
			n += 1 + l + sovTracerPayload(uint64(l))
		}
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTracerPayload(uint64(len(k))) + 1 + len(v) + sovTracerPayload(uint64(len(v)))
			n += mapEntrySize + 1 + sovTracerPayload(uint64(mapEntrySize))
		}
	}
	if m.DroppedTrace {
		n += 2
	}
	return n
}

func (m *TracerPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	l = len(m.LanguageName)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	l = len(m.LanguageVersion)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	l = len(m.TracerVersion)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	l = len(m.RuntimeID)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	if len(m.Chunks) > 0 {
		for _, e := range m.Chunks {
			l = e.Size()
			n += 1 + l + sovTracerPayload(uint64(l))
		}
	}
	if len(m.Tags) > 0 {
		for k, v := range m.Tags {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTracerPayload(uint64(len(k))) + 1 + len(v) + sovTracerPayload(uint64(len(v)))
			n += mapEntrySize + 1 + sovTracerPayload(uint64(mapEntrySize))
		}
	}
	l = len(m.Env)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	l = len(m.AppVersion)
	if l > 0 {
		n += 1 + l + sovTracerPayload(uint64(l))
	}
	return n
}

func sovTracerPayload(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTracerPayload(x uint64) (n int) {
	return sovTracerPayload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TraceChunk) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForSpans := "[]*Span{"
	for _, f := range this.Spans {
		repeatedStringForSpans += strings.Replace(fmt.Sprintf("%v", f), "Span", "Span", 1) + ","
	}
	repeatedStringForSpans += "}"
	keysForTags := make([]string, 0, len(this.Tags))
	for k, _ := range this.Tags {
		keysForTags = append(keysForTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTags)
	mapStringForTags := "map[string]string{"
	for _, k := range keysForTags {
		mapStringForTags += fmt.Sprintf("%v: %v,", k, this.Tags[k])
	}
	mapStringForTags += "}"
	s := strings.Join([]string{`&TraceChunk{`,
		`Priority:` + fmt.Sprintf("%v", this.Priority) + `,`,
		`Origin:` + fmt.Sprintf("%v", this.Origin) + `,`,
		`Spans:` + repeatedStringForSpans + `,`,
		`Tags:` + mapStringForTags + `,`,
		`DroppedTrace:` + fmt.Sprintf("%v", this.DroppedTrace) + `,`,
		`}`,
	}, "")
	return s
}
func (this *TracerPayload) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForChunks := "[]*TraceChunk{"
	for _, f := range this.Chunks {
		repeatedStringForChunks += strings.Replace(f.String(), "TraceChunk", "TraceChunk", 1) + ","
	}
	repeatedStringForChunks += "}"
	keysForTags := make([]string, 0, len(this.Tags))
	for k, _ := range this.Tags {
		keysForTags = append(keysForTags, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForTags)
	mapStringForTags := "map[string]string{"
	for _, k := range keysForTags {
		mapStringForTags += fmt.Sprintf("%v: %v,", k, this.Tags[k])
	}
	mapStringForTags += "}"
	s := strings.Join([]string{`&TracerPayload{`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`LanguageName:` + fmt.Sprintf("%v", this.LanguageName) + `,`,
		`LanguageVersion:` + fmt.Sprintf("%v", this.LanguageVersion) + `,`,
		`TracerVersion:` + fmt.Sprintf("%v", this.TracerVersion) + `,`,
		`RuntimeID:` + fmt.Sprintf("%v", this.RuntimeID) + `,`,
		`Chunks:` + repeatedStringForChunks + `,`,
		`Tags:` + mapStringForTags + `,`,
		`Env:` + fmt.Sprintf("%v", this.Env) + `,`,
		`Hostname:` + fmt.Sprintf("%v", this.Hostname) + `,`,
		`AppVersion:` + fmt.Sprintf("%v", this.AppVersion) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTracerPayload(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TraceChunk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracerPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TraceChunk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TraceChunk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Origin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spans", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, &Span{})
			if err := m.Spans[len(m.Spans)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTracerPayload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTracerPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTracerPayload
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTracerPayload
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTracerPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTracerPayload
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthTracerPayload
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTracerPayload(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthTracerPayload
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DroppedTrace", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedTrace = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTracerPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TracerPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTracerPayload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TracerPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TracerPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LanguageName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LanguageName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LanguageVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LanguageVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TracerVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TracerVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RuntimeID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chunks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chunks = append(m.Chunks, &TraceChunk{})
			if err := m.Chunks[len(m.Chunks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tags == nil {
				m.Tags = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTracerPayload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTracerPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTracerPayload
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTracerPayload
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTracerPayload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTracerPayload
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthTracerPayload
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTracerPayload(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthTracerPayload
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Tags[mapkey] = mapvalue
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTracerPayload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AppVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTracerPayload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTracerPayload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTracerPayload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTracerPayload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTracerPayload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTracerPayload
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTracerPayload
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTracerPayload
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTracerPayload        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTracerPayload          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTracerPayload = fmt.Errorf("proto: unexpected end of group")
)
