// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intake/apiv2/apiv2.proto

package apiv2

import (
	fmt "fmt"
	math "math"

	origin "github.com/DataDog/datadog-agent/origin"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetricType int32

const (
	MetricType_GAUGE MetricType = 0
	MetricType_COUNT MetricType = 1
	MetricType_RATE  MetricType = 2
)

var MetricType_name = map[int32]string{
	0: "GAUGE",
	1: "COUNT",
	2: "RATE",
}

var MetricType_value = map[string]int32{
	"GAUGE": 0,
	"COUNT": 1,
	"RATE":  2,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}

func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{0}
}

type MetricPoint struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricPoint) Reset()         { *m = MetricPoint{} }
func (m *MetricPoint) String() string { return proto.CompactTextString(m) }
func (*MetricPoint) ProtoMessage()    {}
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{0}
}

func (m *MetricPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricPoint.Unmarshal(m, b)
}
func (m *MetricPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricPoint.Marshal(b, m, deterministic)
}
func (m *MetricPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricPoint.Merge(m, src)
}
func (m *MetricPoint) XXX_Size() int {
	return xxx_messageInfo_MetricPoint.Size(m)
}
func (m *MetricPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricPoint.DiscardUnknown(m)
}

var xxx_messageInfo_MetricPoint proto.InternalMessageInfo

func (m *MetricPoint) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *MetricPoint) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Resource struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{1}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Metadata struct {
	Origin               *origin.Origin `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{2}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetOrigin() *origin.Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type MetricSeries struct {
	Resources            []*Resource    `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Metric               string         `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags                 []string       `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Points               []*MetricPoint `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	Type                 MetricType     `protobuf:"varint,5,opt,name=type,proto3,enum=datadoghq.api.series.v2.MetricType" json:"type,omitempty"`
	Unit                 string         `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	SourceTypeName       string         `protobuf:"bytes,7,opt,name=source_type_name,json=sourceTypeName,proto3" json:"source_type_name,omitempty"`
	Interval             int64          `protobuf:"varint,8,opt,name=interval,proto3" json:"interval,omitempty"`
	Metadata             *Metadata      `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MetricSeries) Reset()         { *m = MetricSeries{} }
func (m *MetricSeries) String() string { return proto.CompactTextString(m) }
func (*MetricSeries) ProtoMessage()    {}
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{3}
}

func (m *MetricSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricSeries.Unmarshal(m, b)
}
func (m *MetricSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricSeries.Marshal(b, m, deterministic)
}
func (m *MetricSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricSeries.Merge(m, src)
}
func (m *MetricSeries) XXX_Size() int {
	return xxx_messageInfo_MetricSeries.Size(m)
}
func (m *MetricSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricSeries.DiscardUnknown(m)
}

var xxx_messageInfo_MetricSeries proto.InternalMessageInfo

func (m *MetricSeries) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *MetricSeries) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *MetricSeries) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *MetricSeries) GetPoints() []*MetricPoint {
	if m != nil {
		return m.Points
	}
	return nil
}

func (m *MetricSeries) GetType() MetricType {
	if m != nil {
		return m.Type
	}
	return MetricType_GAUGE
}

func (m *MetricSeries) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *MetricSeries) GetSourceTypeName() string {
	if m != nil {
		return m.SourceTypeName
	}
	return ""
}

func (m *MetricSeries) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *MetricSeries) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type MetricPayload struct {
	Series               []*MetricSeries `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MetricPayload) Reset()         { *m = MetricPayload{} }
func (m *MetricPayload) String() string { return proto.CompactTextString(m) }
func (*MetricPayload) ProtoMessage()    {}
func (*MetricPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{4}
}

func (m *MetricPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricPayload.Unmarshal(m, b)
}
func (m *MetricPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricPayload.Marshal(b, m, deterministic)
}
func (m *MetricPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricPayload.Merge(m, src)
}
func (m *MetricPayload) XXX_Size() int {
	return xxx_messageInfo_MetricPayload.Size(m)
}
func (m *MetricPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricPayload.DiscardUnknown(m)
}

var xxx_messageInfo_MetricPayload proto.InternalMessageInfo

func (m *MetricPayload) GetSeries() []*MetricSeries {
	if m != nil {
		return m.Series
	}
	return nil
}

type Response struct {
	Errors               []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c28b0384f35aa131, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrors() []string {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterEnum("datadoghq.api.series.v2.MetricType", MetricType_name, MetricType_value)
	proto.RegisterType((*MetricPoint)(nil), "datadoghq.api.series.v2.MetricPoint")
	proto.RegisterType((*Resource)(nil), "datadoghq.api.series.v2.Resource")
	proto.RegisterType((*Metadata)(nil), "datadoghq.api.series.v2.Metadata")
	proto.RegisterType((*MetricSeries)(nil), "datadoghq.api.series.v2.MetricSeries")
	proto.RegisterType((*MetricPayload)(nil), "datadoghq.api.series.v2.MetricPayload")
	proto.RegisterType((*Response)(nil), "datadoghq.api.series.v2.Response")
}

func init() {
	proto.RegisterFile("intake/apiv2/apiv2.proto", fileDescriptor_c28b0384f35aa131)
}

var fileDescriptor_c28b0384f35aa131 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xc9, 0xda, 0x86, 0xe4, 0x15, 0xaa, 0xca, 0x42, 0x60, 0x0d, 0x0e, 0x59, 0xf8, 0xa1,
	0x68, 0x1a, 0x89, 0x14, 0x0e, 0x5c, 0x98, 0x50, 0x61, 0xd3, 0x4e, 0xeb, 0x90, 0xe9, 0x2e, 0x5c,
	0x26, 0xb7, 0xb1, 0x32, 0x8b, 0x26, 0x36, 0xb6, 0x5b, 0xa9, 0x7f, 0x03, 0xff, 0x34, 0xf2, 0x0f,
	0x56, 0x2e, 0x63, 0x97, 0xfa, 0x3d, 0xdb, 0x9f, 0xfa, 0xfb, 0xbe, 0x2f, 0x0f, 0x30, 0xef, 0x0d,
	0xfd, 0xc9, 0x2a, 0x2a, 0xf9, 0xb6, 0xf6, 0xbf, 0xa5, 0x54, 0xc2, 0x08, 0xf4, 0xa2, 0xa1, 0x86,
	0x36, 0xa2, 0xbd, 0xfd, 0x55, 0x52, 0xc9, 0x4b, 0xcd, 0x14, 0x67, 0xba, 0xdc, 0xd6, 0x87, 0x2f,
	0x3b, 0x66, 0x14, 0x5f, 0xe9, 0x4a, 0x28, 0xde, 0xf2, 0x3e, 0x2c, 0x9e, 0xca, 0x67, 0x30, 0xbe,
	0x74, 0xc7, 0xdf, 0x04, 0xef, 0x0d, 0x7a, 0x06, 0xa3, 0x2d, 0x5d, 0x6f, 0x18, 0x8e, 0xb2, 0xa8,
	0x88, 0x88, 0x4f, 0xd0, 0x2b, 0x48, 0x0d, 0xef, 0x98, 0x36, 0xb4, 0x93, 0xf8, 0x20, 0x8b, 0x8a,
	0x01, 0xd9, 0x6f, 0xe4, 0x35, 0x24, 0x84, 0x69, 0xb1, 0x51, 0x2b, 0x86, 0x10, 0x0c, 0xcd, 0x4e,
	0x7a, 0x3c, 0x25, 0x2e, 0xb6, 0x7b, 0x3d, 0xed, 0x98, 0x03, 0x53, 0xe2, 0x62, 0xcb, 0x5c, 0x32,
	0x43, 0xad, 0x64, 0xf4, 0x0e, 0x62, 0x2f, 0xc9, 0x51, 0xe3, 0x7a, 0x52, 0x06, 0x85, 0x57, 0x6e,
	0x21, 0xe1, 0x34, 0xff, 0x3d, 0x80, 0x27, 0x5e, 0xeb, 0x77, 0x57, 0x1b, 0xfa, 0x0c, 0xa9, 0x0a,
	0x0f, 0x6b, 0x1c, 0x65, 0x83, 0x62, 0x5c, 0x1f, 0x95, 0xf7, 0xb8, 0x50, 0xfe, 0x95, 0x48, 0xf6,
	0x0c, 0x7a, 0x0e, 0xb1, 0xf7, 0x26, 0x68, 0x0b, 0x99, 0xab, 0x82, 0xb6, 0x1a, 0x0f, 0xb2, 0x81,
	0xab, 0x82, 0xb6, 0x1a, 0x7d, 0x82, 0x58, 0x5a, 0x8b, 0x34, 0x1e, 0xba, 0x97, 0xde, 0xdc, 0xfb,
	0xd2, 0x3f, 0x7e, 0x92, 0xc0, 0xa0, 0x8f, 0xc1, 0x97, 0x51, 0x16, 0x15, 0x93, 0xfa, 0xf5, 0x03,
	0xec, 0x62, 0x27, 0xd9, 0xde, 0xbc, 0x4d, 0xcf, 0x0d, 0x8e, 0xbd, 0x79, 0x36, 0x46, 0x05, 0x4c,
	0x7d, 0x05, 0x37, 0xf6, 0xca, 0x8d, 0x33, 0xf7, 0xb1, 0x3b, 0x9f, 0xf8, 0x7d, 0xcb, 0xcf, 0x69,
	0xc7, 0xd0, 0x21, 0x24, 0xbc, 0x37, 0x4c, 0x6d, 0xe9, 0x1a, 0x27, 0xae, 0x6f, 0x77, 0x39, 0x3a,
	0x85, 0xa4, 0x0b, 0x2d, 0xc0, 0xa9, 0x33, 0xfe, 0xe8, 0x7f, 0xb2, 0xdc, 0x45, 0x72, 0x87, 0xe4,
	0x73, 0x78, 0x1a, 0x0a, 0xa5, 0xbb, 0xb5, 0xa0, 0x0d, 0x3a, 0x85, 0xd8, 0x03, 0xa1, 0x15, 0x6f,
	0x1f, 0x28, 0xd2, 0x37, 0x91, 0x04, 0x28, 0xcf, 0xdd, 0x57, 0x24, 0x45, 0xaf, 0x99, 0xed, 0x0b,
	0x53, 0x4a, 0x28, 0xff, 0x57, 0x29, 0x09, 0xd9, 0xf1, 0x09, 0xc0, 0xde, 0x20, 0x94, 0xc2, 0xe8,
	0x62, 0x76, 0x7d, 0x71, 0x3e, 0x7d, 0x64, 0xc3, 0xaf, 0x57, 0xd7, 0xf3, 0xc5, 0x34, 0x42, 0x09,
	0x0c, 0xc9, 0x6c, 0x71, 0x3e, 0x3d, 0xf8, 0x72, 0xf2, 0xe3, 0xb8, 0xe5, 0xe6, 0x76, 0xb3, 0x2c,
	0x57, 0xa2, 0xab, 0xce, 0xa8, 0xa1, 0x67, 0xa2, 0xad, 0x9a, 0xe6, 0x7d, 0x2b, 0x2a, 0xb9, 0xac,
	0xfc, 0x20, 0xc9, 0xa5, 0x1f, 0xa2, 0x65, 0xec, 0xe6, 0xe1, 0xc3, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x66, 0xa0, 0x16, 0x55, 0x61, 0x03, 0x00, 0x00,
}
