// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -fsigned-char /git/datadog-agent/pkg/network/ebpf/conntrack_types.go

package ebpf

type In6Addr struct {
	U [16]byte
}

type ConntrackTuple struct {
	Saddr    In6Addr
	Daddr    In6Addr
	Sport    uint16
	Dport    uint16
	Netns    uint32
	Metadata uint32
	X_pad    uint32
}

type ConntrackTelemetry struct {
	Registers uint64
	Dropped   uint64
}
